name: Emma
favicon: null
layout_spectrum: 0.967425137758255
typography_spectrum: 0.8414526823908091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5361345265991986
  lightness: 0.7061030592303723
  saturation: 0.13885666336864233
  rhythmicContrast: 0.7495640022680163
purpose: []
